package com.example.debtmanager;
import android.app.*;import android.os.*;import android.database.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class CustomerActivity extends Activity{
 Db db;long cid;LinearLayout list;TextView head;String customerName="";
 public void onCreate(Bundle b){super.onCreate(b);cid=getIntent().getLongExtra("id",0);db=new Db(this);build();}
 String fmt(double x){return String.format(java.util.Locale.US,"%,.0f",x);}
 void build(){ScrollView sv=new ScrollView(this);LinearLayout r=Ui.root(this);head=Ui.title(this,"ملف العميل");r.addView(head);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);Button add=Ui.btn(this,"＋ إضافة سلعة / عقد تقسيط");add.setOnClickListener(v->addItem());r.addView(add);sv.addView(r);setContentView(sv);refresh();}
 void refresh(){list.removeAllViews();Cursor c=db.customer(cid);if(c.moveToFirst()){customerName=c.getString(1);head.setText("ملف العميل: "+customerName+"\nالهاتف: "+c.getString(2));}c.close();Cursor x=db.items(cid);double total=0,paid=0;while(x.moveToNext()){long iid=x.getLong(0);String name=x.getString(2);double cash=x.getDouble(3),inst=x.getDouble(4),term=x.getInt(5),each=x.getDouble(6),p=x.getDouble(x.getColumnIndexOrThrow("paid"));total+=inst;paid+=p;double rem=Math.max(0,inst-p);TextView card=Ui.card(this,name+"\nالسعر الأصلي: "+fmt(cash)+" د.ع\nسعر التقسيط: "+fmt(inst)+" د.ع   |   الربح: "+fmt(inst-cash)+" د.ع\nالقسط: "+fmt(each)+" د.ع   |   المتبقي: "+fmt(rem)+" د.ع\nالأقساط المتبقية تقريباً: "+(each>0?Math.ceil(rem/each):0));card.setOnClickListener(v->payments(iid,name,inst,p,each));list.addView(card);}x.close();TextView sum=Ui.card(this,"إجمالي التقسيط: "+fmt(total)+" د.ع\nإجمالي المدفوع: "+fmt(paid)+" د.ع\nإجمالي المتبقي: "+fmt(Math.max(0,total-paid))+" د.ع");list.addView(sum,0);}
 void addItem(){LinearLayout l=Ui.root(this);EditText n=Ui.edit(this,"اسم السلعة"),cash=Ui.edit(this,"السعر الأصلي (د.ع)"),inst=Ui.edit(this,"سعر التقسيط (د.ع)"),term=Ui.edit(this,"عدد الأشهر / الأقساط"),each=Ui.edit(this,"قيمة القسط الواحد (د.ع)");l.addView(n);l.addView(cash);l.addView(inst);l.addView(term);l.addView(each);TextView hint=Ui.label(this,"إذا تركت قيمة القسط فارغة سيحسبها البرنامج تلقائياً من سعر التقسيط ÷ عدد الأقساط.");l.addView(hint);new AlertDialog.Builder(this).setTitle("إضافة سلعة").setView(l).setPositiveButton("حفظ",(d,w)->{double iv=Ui.num(inst),cv=Ui.num(cash);int tv=Ui.integer(term);double ev=Ui.num(each);if(ev<=0&&tv>0)ev=iv/tv;db.addItem(cid,n.getText().toString(),cv,iv,tv,ev,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));refresh();}).setNegativeButton("إلغاء",null).show();}
 void payments(long iid,String name,double total,double paid,double each){LinearLayout l=Ui.root(this);TextView info=Ui.label(this,"السلعة: "+name+"\nالمتبقي: "+fmt(Math.max(0,total-paid))+" د.ع");EditText amount=Ui.edit(this,"مبلغ الدفعة (د.ع)"),note=Ui.edit(this,"ملاحظة (اختياري)");l.addView(info);l.addView(amount);l.addView(note);new AlertDialog.Builder(this).setTitle("تسجيل دفعة").setView(l).setPositiveButton("تسجيل",(d,w)->{double a=Ui.num(amount);if(a>0)db.addPayment(iid,a,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()),note.getText().toString());refresh();}).setNeutralButton("سجل الدفعات",(d,w)->paymentHistory(iid,name)).setNegativeButton("إلغاء",null).show();}
 void paymentHistory(long iid,String name){StringBuilder s=new StringBuilder("سجل دفعات "+name+"\n\n");Cursor c=db.getReadableDatabase().rawQuery("SELECT date,amount,note FROM payments WHERE item_id=? ORDER BY id DESC",new String[]{""+iid});if(!c.moveToFirst())s.append("لا توجد دفعات مسجلة.");else do{s.append(c.getString(0)).append("  —  ").append(fmt(c.getDouble(1))).append(" د.ع");if(!c.getString(2).isEmpty())s.append("\n").append(c.getString(2));s.append("\n\n");}while(c.moveToNext());c.close();new AlertDialog.Builder(this).setTitle("سجل الدفعات").setMessage(s.toString()).setPositiveButton("إغلاق",null).show();}
}
