package com.example.debtmanager;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class CustomerActivity extends Activity{
 Db db;long cid;LinearLayout list;TextView head,nameLine,phoneLine,addressLine,totalV,paidV,remainV,countV;String customerName="";FrameLayout frame;View shade;LinearLayout drawer;ScrollView scroll;
 public void onCreate(Bundle b){super.onCreate(b);cid=getIntent().getLongExtra("id",0);db=new Db(this);getWindow().setStatusBarColor(Ui.NAVY);build();}
 String fmt(double x){return String.format(Locale.US,"%,.0f",x);} int dp(int x){return Ui.dp(this,x);}
 void build(){
  frame=new FrameLayout(this);scroll=new ScrollView(this);LinearLayout r=Ui.root(this);scroll.addView(r);frame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));buildHeader(r);buildProfile(r);buildStats(r);buildProducts(r);buildDrawer();setContentView(frame);refresh();
 }
 void buildHeader(LinearLayout r){
  LinearLayout top=Ui.row(this);TextView back=Ui.iconButton(this,"‹");back.setTextSize(34);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));
  LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.setGravity(Gravity.RIGHT);head=Ui.title(this,"ملف العميل");tt.addView(head);tt.addView(Ui.subtitle(this,"تفاصيل المشتريات والدفعات"));top.addView(tt,new LinearLayout.LayoutParams(0,dp(58),1));TextView menu=Ui.iconButton(this,"☰");menu.setOnClickListener(v->toggleDrawer(true));top.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(48)));r.addView(top);
  LinearLayout actions=Ui.row(this);Button edit=Ui.btn(this,"✏  تعديل بيانات العميل"),del=Ui.outlineBtn(this,"🗑  حذف العميل",Ui.RED);edit.setOnClickListener(v->editCustomer());del.setOnClickListener(v->deleteCustomer());actions.addView(edit,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(del,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(actions);
 }
 void buildProfile(LinearLayout r){
  LinearLayout profile=Ui.panel(this);TextView avatar=Ui.txt(this,"أ",24,Color.WHITE);avatar.setGravity(Gravity.CENTER);avatar.setBackground(Ui.bg(Ui.BLUE,Ui.BLUE,60));profile.addView(avatar,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);nameLine=Ui.txt(this,"",19,Ui.TEXT);nameLine.setTypeface(null,1);phoneLine=Ui.txt(this,"",13,Ui.MUTED);addressLine=Ui.txt(this,"",13,Ui.MUTED);info.addView(nameLine);info.addView(phoneLine);info.addView(addressLine);profile.addView(info,new LinearLayout.LayoutParams(0,-2,1));r.addView(profile);
 }
 void buildStats(LinearLayout r){LinearLayout sr1=Ui.row(this),sr2=Ui.row(this);LinearLayout x1=Ui.stat(this,"إجمالي التقسيط","0 د.ع",Ui.BLUE),x2=Ui.stat(this,"إجمالي المدفوع","0 د.ع",Ui.GREEN),x3=Ui.stat(this,"المتبقي","0 د.ع",Ui.RED),x4=Ui.stat(this,"عدد المشتريات","0",Ui.AMBER);totalV=(TextView)x1.getChildAt(1);paidV=(TextView)x2.getChildAt(1);remainV=(TextView)x3.getChildAt(1);countV=(TextView)x4.getChildAt(1);sr1.addView(x1,new LinearLayout.LayoutParams(0,-2,1));sr1.addView(x2,new LinearLayout.LayoutParams(0,-2,1));sr2.addView(x3,new LinearLayout.LayoutParams(0,-2,1));sr2.addView(x4,new LinearLayout.LayoutParams(0,-2,1));r.addView(sr1);r.addView(sr2);}
 void buildProducts(LinearLayout r){LinearLayout ph=Ui.row(this);LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.addView(Ui.title(this,"المشتريات"));tt.addView(Ui.subtitle(this,"السعر الأصلي وسعر التقسيط والربح والدفعات"));ph.addView(tt,new LinearLayout.LayoutParams(0,-2,1));Button add=Ui.btn(this,"＋ إضافة سلعة");add.setOnClickListener(v->addItem());ph.addView(add,new LinearLayout.LayoutParams(dp(135),dp(48)));r.addView(ph);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);}
 void refresh(){list.removeAllViews();Cursor c=db.customer(cid);if(c.moveToFirst()){customerName=c.getString(1);head.setText(customerName);nameLine.setText(customerName);phoneLine.setText("📞  "+safe(c.getString(2)));addressLine.setText("📍  "+safe(c.getString(3)));}else{finish();return;}c.close();Cursor x=db.items(cid);double total=0,paid=0;int contracts=0;while(x.moveToNext()){contracts++;long iid=x.getLong(0);String item=x.getString(2);double cash=x.getDouble(3),inst=x.getDouble(4),each=x.getDouble(6),p=x.getDouble(x.getColumnIndexOrThrow("paid"));total+=inst;paid+=p;double rem=Math.max(0,inst-p);list.addView(productCard(iid,item,cash,inst,each,p,rem,x.getInt(5),x.getString(7)));}x.close();totalV.setText(fmt(total)+" د.ع");paidV.setText(fmt(paid)+" د.ع");remainV.setText(fmt(Math.max(0,total-paid))+" د.ع");countV.setText(""+contracts);}
 String safe(String s){return s==null?"":s;}
 LinearLayout productCard(long iid,String item,double cash,double inst,double each,double paid,double rem,int term,String startDate){
  LinearLayout card=Ui.panel(this);card.setOrientation(LinearLayout.VERTICAL);LinearLayout line=Ui.row(this);TextView n=Ui.txt(this,item,18,Ui.TEXT);n.setTypeface(null,1);line.addView(n,new LinearLayout.LayoutParams(0,-2,1));line.addView(Ui.chip(this,rem<=0?"مسدد":"قيد التقسيط",rem<=0?Color.rgb(220,252,231):Color.rgb(219,234,254),rem<=0?Ui.GREEN:Ui.BLUE));card.addView(line);
  card.addView(Ui.txt(this,"السعر الأصلي     "+fmt(cash)+" د.ع",14,Ui.MUTED));card.addView(Ui.txt(this,"سعر التقسيط     "+fmt(inst)+" د.ع",14,Ui.TEXT));card.addView(Ui.txt(this,"الربح             "+fmt(inst-cash)+" د.ع",14,Ui.GREEN));card.addView(Ui.txt(this,"المدفوع          "+fmt(paid)+" د.ع",14,Ui.TEXT));card.addView(Ui.txt(this,"المتبقي          "+fmt(rem)+" د.ع",14,rem>0?Ui.RED:Ui.GREEN));card.addView(Ui.txt(this,"القسط             "+fmt(each)+" د.ع   •   المتبقي "+(each>0?Math.ceil(rem/each):0)+" من "+term,13,Ui.MUTED));
  Button pay=Ui.btn(this,"＋ تسجيل دفعة");pay.setOnClickListener(v->payments(iid,item,inst,paid,each));card.addView(pay,new LinearLayout.LayoutParams(-1,dp(46)));
  LinearLayout actions=Ui.row(this);Button ep=Ui.outlineBtn(this,"✏  تعديل السلعة",Ui.BLUE),dp=Ui.outlineBtn(this,"🗑  حذف السلعة",Ui.RED),hp=Ui.outlineBtn(this,"☷  سجل الدفعات",Ui.NAVY);ep.setOnClickListener(v->editItem(iid,item,cash,inst,term,each,startDate));dp.setOnClickListener(v->deleteItem(iid,item));hp.setOnClickListener(v->paymentHistory(iid,item));actions.addView(ep,new LinearLayout.LayoutParams(0,dp(46),1));actions.addView(dp,new LinearLayout.LayoutParams(0,dp(46),1));actions.addView(hp,new LinearLayout.LayoutParams(0,dp(46),1));card.addView(actions);return card;
 }
 void editCustomer(){Cursor c=db.customer(cid);if(!c.moveToFirst()){c.close();return;}String oldN=safe(c.getString(1)),oldP=safe(c.getString(2)),oldA=safe(c.getString(3));c.close();LinearLayout l=Ui.root(this);EditText n=Ui.edit(this,"اسم العميل *"),p=Ui.edit(this,"رقم الهاتف"),a=Ui.edit(this,"العنوان");n.setText(oldN);p.setText(oldP);a.setText(oldA);l.addView(n);l.addView(p);l.addView(a);new AlertDialog.Builder(this).setTitle("تعديل بيانات العميل").setView(l).setPositiveButton("حفظ التعديلات",(d,w)->{String nn=n.getText().toString().trim();if(nn.isEmpty()){Toast.makeText(this,"اسم العميل مطلوب",Toast.LENGTH_SHORT).show();return;}db.updateCustomer(cid,nn,p.getText().toString().trim(),a.getText().toString().trim());refresh();}).setNegativeButton("إلغاء",null).show();}
 void deleteCustomer(){new AlertDialog.Builder(this).setTitle("حذف العميل نهائياً").setMessage("سيتم حذف العميل وجميع السلع والدفعات المرتبطة به. لا يمكن التراجع عن الحذف إلا باستعادة نسخة احتياطية.").setPositiveButton("حذف نهائياً",(d,w)->{db.deleteCustomer(cid);finish();}).setNegativeButton("إلغاء",null).show();}
 void addItem(){showItemDialog("إضافة سلعة",0,"",0,0,0,0,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()),false);}
 void editItem(long iid,String item,double cash,double inst,int term,double each,String date){showItemDialog("تعديل السلعة",iid,item,cash,inst,term,each,date,true);}
 void showItemDialog(String title,long iid,String oldName,double cash,double inst,int term,double each,String date,boolean editing){LinearLayout l=Ui.root(this);EditText n=Ui.edit(this,"اسم السلعة *"),cv=Ui.edit(this,"السعر الأصلي (د.ع)"),iv=Ui.edit(this,"سعر التقسيط (د.ع)"),tv=Ui.edit(this,"عدد الأقساط / الأشهر"),ev=Ui.edit(this,"قيمة القسط الواحد (د.ع)");n.setText(oldName);if(editing){cv.setText(fmt(cash));iv.setText(fmt(inst));tv.setText(""+term);ev.setText(fmt(each));}l.addView(n);l.addView(cv);l.addView(iv);l.addView(tv);l.addView(ev);l.addView(Ui.label(this,"يمكن ترك قيمة القسط فارغة ليحسبها البرنامج تلقائياً."));new AlertDialog.Builder(this).setTitle(title).setView(l).setPositiveButton("حفظ",(d,w)->{double c=Ui.num(cv),i=Ui.num(iv),e=Ui.num(ev);int t=Ui.integer(tv);if(e<=0&&t>0)e=i/t;String nn=n.getText().toString().trim();if(nn.isEmpty()){Toast.makeText(this,"اسم السلعة مطلوب",Toast.LENGTH_SHORT).show();return;}if(editing)db.updateItem(iid,nn,c,i,t,e,date);else db.addItem(cid,nn,c,i,t,e,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));refresh();}).setNegativeButton("إلغاء",null).show();}
 void deleteItem(long iid,String item){new AlertDialog.Builder(this).setTitle("حذف السلعة").setMessage("سيتم حذف "+item+" وجميع دفعاتها نهائياً.").setPositiveButton("حذف",(d,w)->{db.deleteItem(iid);refresh();}).setNegativeButton("إلغاء",null).show();}
 void payments(long iid,String item,double total,double paid,double each){LinearLayout l=Ui.root(this);l.addView(Ui.label(this,"السلعة: "+item+"\nالمتبقي قبل الدفع: "+fmt(Math.max(0,total-paid))+" د.ع"));EditText amount=Ui.edit(this,"مبلغ الدفعة (د.ع)"),note=Ui.edit(this,"ملاحظة (اختياري)");l.addView(amount);l.addView(note);new AlertDialog.Builder(this).setTitle("تسجيل دفعة").setView(l).setPositiveButton("حفظ الدفعة",(d,w)->{double a=Ui.num(amount);if(a>0)db.addPayment(iid,a,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()),note.getText().toString().trim());refresh();}).setNeutralButton("سجل الدفعات",(d,w)->paymentHistory(iid,item)).setNegativeButton("إلغاء",null).show();}
 void paymentHistory(long iid,String item){StringBuilder s=new StringBuilder();Cursor c=db.getReadableDatabase().rawQuery("SELECT date,amount,note FROM payments WHERE item_id=? ORDER BY id DESC",new String[]{""+iid});if(!c.moveToFirst())s.append("لا توجد دفعات مسجلة.");else do{s.append(c.getString(0)).append("  •  ").append(fmt(c.getDouble(1))).append(" د.ع");if(c.getString(2)!=null&&!c.getString(2).isEmpty())s.append("\n").append(c.getString(2));s.append("\n\n");}while(c.moveToNext());c.close();new AlertDialog.Builder(this).setTitle("سجل دفعات: "+item).setMessage(s.toString()).setPositiveButton("إغلاق",null).show();}
 void buildDrawer(){shade=new View(this);shade.setBackgroundColor(0x66000000);shade.setVisibility(View.GONE);shade.setOnClickListener(v->toggleDrawer(false));frame.addView(shade,new FrameLayout.LayoutParams(-1,-1));drawer=new LinearLayout(this);drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(dp(18),dp(24),dp(18),dp(20));drawer.setBackgroundColor(Color.WHITE);drawer.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(300),-1,Gravity.RIGHT);drawer.setVisibility(View.GONE);frame.addView(drawer,p);
  LinearLayout brand=Ui.panel(this);brand.setOrientation(LinearLayout.VERTICAL);TextView b=Ui.txt(this,"💼  ديوني",22,Ui.NAVY);b.setTypeface(null,1);brand.addView(b);brand.addView(Ui.txt(this,"القائمة الرئيسية",13,Ui.MUTED));drawer.addView(brand);
  menuItem("⌂","الرئيسية",()->{toggleDrawer(false);finish();});menuItem("👥","العملاء",()->{toggleDrawer(false);finish();});menuItem("↩","رجوع",()->{toggleDrawer(false);finish();});
 }
 void menuItem(String icon,String title,final Runnable run){TextView t=Ui.txt(this,icon+"    "+title,16,Ui.TEXT);t.setPadding(dp(12),0,dp(12),0);t.setOnClickListener(v->run.run());drawer.addView(t,new LinearLayout.LayoutParams(-1,dp(56)));}
 void toggleDrawer(boolean show){drawer.setVisibility(show?View.VISIBLE:View.GONE);shade.setVisibility(show?View.VISIBLE:View.GONE);}
 @Override public void onBackPressed(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){toggleDrawer(false);return;}super.onBackPressed();}
}
