package com.example.debtmanager;

import android.app.*;import android.os.*;import android.database.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class CustomerActivity extends Activity{
 Db db;long cid;LinearLayout list;TextView head,nameLine,phoneLine,addressLine,totalV,paidV,remainV,countV;String customerName="";
 public void onCreate(Bundle b){super.onCreate(b);cid=getIntent().getLongExtra("id",0);db=new Db(this);build();}
 String fmt(double x){return String.format(Locale.US,"%,.0f",x);}
 void build(){ScrollView sv=new ScrollView(this);LinearLayout r=Ui.root(this);sv.addView(r);setContentView(sv);
  LinearLayout top=Ui.row(this);TextView back=Ui.txt(this,"‹",34,Ui.NAVY);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(45,55));LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);head=Ui.title(this,"ملف العميل");tt.addView(head);tt.addView(Ui.subtitle(this,"تفاصيل المشتريات والدفعات"));top.addView(tt,new LinearLayout.LayoutParams(0,-2,1));Button edit=Ui.btn(this,"تعديل");edit.setOnClickListener(v->editCustomer());top.addView(edit,new LinearLayout.LayoutParams(-2,52));Button del=Ui.btn(this,"حذف");del.setTextColor(Color.rgb(185,28,28));del.setOnClickListener(v->deleteCustomer());top.addView(del,new LinearLayout.LayoutParams(-2,52));r.addView(top);
  LinearLayout profile=Ui.panel(this);TextView avatar=Ui.txt(this,"أ",24,Color.WHITE);avatar.setGravity(Gravity.CENTER);avatar.setBackground(Ui.bg(Ui.BLUE,Ui.BLUE,60));profile.addView(avatar,new LinearLayout.LayoutParams(58,58));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);nameLine=Ui.txt(this,"",18,Ui.TEXT);nameLine.setTypeface(null,1);phoneLine=Ui.txt(this,"",13,Ui.MUTED);addressLine=Ui.txt(this,"",13,Ui.MUTED);info.addView(nameLine);info.addView(phoneLine);info.addView(addressLine);profile.addView(info,new LinearLayout.LayoutParams(0,-2,1));r.addView(profile);
  LinearLayout sr1=Ui.row(this),sr2=Ui.row(this);LinearLayout x1=Ui.stat(this,"إجمالي التقسيط","0 د.ع",Ui.BLUE),x2=Ui.stat(this,"إجمالي المدفوع","0 د.ع",Ui.GREEN),x3=Ui.stat(this,"المتبقي","0 د.ع",Ui.RED),x4=Ui.stat(this,"عدد المشتريات","0",Ui.AMBER);totalV=(TextView)x1.getChildAt(1);paidV=(TextView)x2.getChildAt(1);remainV=(TextView)x3.getChildAt(1);countV=(TextView)x4.getChildAt(1);sr1.addView(x1,new LinearLayout.LayoutParams(0,-2,1));sr1.addView(x2,new LinearLayout.LayoutParams(0,-2,1));sr2.addView(x3,new LinearLayout.LayoutParams(0,-2,1));sr2.addView(x4,new LinearLayout.LayoutParams(0,-2,1));r.addView(sr1);r.addView(sr2);
  LinearLayout ph=Ui.row(this);TextView pt=Ui.title(this,"المشتريات");pt.setTextSize(19);ph.addView(pt,new LinearLayout.LayoutParams(0,-2,1));Button add=Ui.btn(this,"＋ إضافة سلعة");add.setOnClickListener(v->addItem());ph.addView(add,new LinearLayout.LayoutParams(-2,52));r.addView(ph);
  list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);refresh(); }
 void refresh(){list.removeAllViews();Cursor c=db.customer(cid);if(c.moveToFirst()){customerName=c.getString(1);head.setText(customerName);nameLine.setText(customerName);phoneLine.setText("📞  "+c.getString(2));addressLine.setText("📍  "+c.getString(3));}else{finish();return;}c.close();Cursor x=db.items(cid);double total=0,paid=0;int contracts=0;while(x.moveToNext()){contracts++;long iid=x.getLong(0);String item=x.getString(2);double cash=x.getDouble(3),inst=x.getDouble(4),each=x.getDouble(6),p=x.getDouble(x.getColumnIndexOrThrow("paid"));total+=inst;paid+=p;double rem=Math.max(0,inst-p);list.addView(productCard(iid,item,cash,inst,each,p,rem,x.getInt(5),x.getString(7)));}x.close();totalV.setText(fmt(total)+" د.ع");paidV.setText(fmt(paid)+" د.ع");remainV.setText(fmt(Math.max(0,total-paid))+" د.ع");countV.setText(""+contracts); }
 LinearLayout productCard(long iid,String item,double cash,double inst,double each,double paid,double rem,int term,String startDate){LinearLayout card=Ui.panel(this);LinearLayout main=new LinearLayout(this);main.setOrientation(LinearLayout.VERTICAL);LinearLayout line=Ui.row(this);TextView n=Ui.txt(this,item,17,Ui.TEXT);n.setTypeface(null,1);line.addView(n,new LinearLayout.LayoutParams(0,-2,1));line.addView(Ui.chip(this,rem<=0?"مسدد":"قيد التقسيط",rem<=0?Color.rgb(220,252,231):Color.rgb(219,234,254),rem<=0?Ui.GREEN:Ui.BLUE));main.addView(line);main.addView(Ui.txt(this,"السعر النقدي: "+fmt(cash)+" د.ع",13,Ui.MUTED));main.addView(Ui.txt(this,"سعر التقسيط: "+fmt(inst)+" د.ع     الربح: "+fmt(inst-cash)+" د.ع",13,Ui.TEXT));main.addView(Ui.txt(this,"المدفوع: "+fmt(paid)+" د.ع     المتبقي: "+fmt(rem)+" د.ع",13,Ui.TEXT));main.addView(Ui.txt(this,"القسط: "+fmt(each)+" د.ع     الأقساط المتبقية: "+(each>0?Math.ceil(rem/each):0)+" من "+term,13,Ui.MUTED));
  LinearLayout actions=Ui.row(this);Button ep=Ui.btn(this,"تعديل السلعة");ep.setOnClickListener(v->editItem(iid,item,cash,inst,term,each,startDate));Button dp=Ui.btn(this,"حذف السلعة");dp.setTextColor(Color.rgb(185,28,28));dp.setOnClickListener(v->deleteItem(iid,item));Button pay=Ui.btn(this,"تسجيل دفعة");pay.setOnClickListener(v->payments(iid,item,inst,paid,each));actions.addView(ep,new LinearLayout.LayoutParams(0,50,1));actions.addView(dp,new LinearLayout.LayoutParams(0,50,1));actions.addView(pay,new LinearLayout.LayoutParams(0,50,1));main.addView(actions);
  card.addView(main,new LinearLayout.LayoutParams(-1,-2));card.setOnClickListener(v->{});return card;}
 void editCustomer(){Cursor c=db.customer(cid);if(!c.moveToFirst()){c.close();return;}String oldN=c.getString(1),oldP=c.getString(2),oldA=c.getString(3);c.close();LinearLayout l=Ui.root(this);EditText n=Ui.edit(this,"اسم العميل *"),p=Ui.edit(this,"رقم الهاتف"),a=Ui.edit(this,"العنوان");n.setText(oldN);p.setText(oldP);a.setText(oldA);l.addView(n);l.addView(p);l.addView(a);new AlertDialog.Builder(this).setTitle("تعديل بيانات العميل").setView(l).setPositiveButton("حفظ التعديلات",(d,w)->{String nn=n.getText().toString().trim();if(!nn.isEmpty()){db.updateCustomer(cid,nn,p.getText().toString().trim(),a.getText().toString().trim());refresh();}}).setNegativeButton("إلغاء",null).show();}
 void deleteCustomer(){new AlertDialog.Builder(this).setTitle("حذف العميل").setMessage("سيتم حذف العميل وجميع سلعه ودفعاته نهائياً من التطبيق. هل أنت متأكد؟").setPositiveButton("حذف نهائياً",(d,w)->{db.deleteCustomer(cid);finish();}).setNegativeButton("إلغاء",null).show();}
 void addItem(){showItemDialog("إضافة سلعة",0,"","",0,0,0,0,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()),false);}
 void editItem(long iid,String item,double cash,double inst,int term,double each,String date){showItemDialog("تعديل السلعة",iid,item,"",cash,inst,term,each,date,true);}
 void showItemDialog(String title,long iid,String oldName,String unused,double cash,double inst,int term,double each,String date,boolean editing){LinearLayout l=Ui.root(this);EditText n=Ui.edit(this,"اسم السلعة *"),cv=Ui.edit(this,"السعر الأصلي (د.ع)"),iv=Ui.edit(this,"سعر التقسيط (د.ع)"),tv=Ui.edit(this,"عدد الأقساط / الأشهر"),ev=Ui.edit(this,"قيمة القسط الواحد (د.ع)");n.setText(oldName);if(editing){cv.setText(fmt(cash));iv.setText(fmt(inst));tv.setText(""+term);ev.setText(fmt(each));}l.addView(n);l.addView(cv);l.addView(iv);l.addView(tv);l.addView(ev);l.addView(Ui.label(this,"اترك قيمة القسط فارغة ليحسبها البرنامج تلقائياً."));new AlertDialog.Builder(this).setTitle(title).setView(l).setPositiveButton("حفظ",(d,w)->{double c=Ui.num(cv),i=Ui.num(iv),e=Ui.num(ev);int t=Ui.integer(tv);if(e<=0&&t>0)e=i/t;String nn=n.getText().toString().trim();if(nn.isEmpty())return;if(editing)db.updateItem(iid,nn,c,i,t,e,date);else db.addItem(cid,nn,c,i,t,e,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));refresh();}).setNegativeButton("إلغاء",null).show();}
 void deleteItem(long iid,String item){new AlertDialog.Builder(this).setTitle("حذف السلعة").setMessage("سيتم حذف "+item+" وجميع دفعاتها نهائياً. هل تريد المتابعة؟").setPositiveButton("حذف",(d,w)->{db.deleteItem(iid);refresh();}).setNegativeButton("إلغاء",null).show();}
 void payments(long iid,String item,double total,double paid,double each){LinearLayout l=Ui.root(this);l.addView(Ui.label(this,"السلعة: "+item+"\nالمتبقي قبل الدفع: "+fmt(Math.max(0,total-paid))+" د.ع"));EditText amount=Ui.edit(this,"مبلغ الدفعة (د.ع)"),note=Ui.edit(this,"ملاحظة (اختياري)");l.addView(amount);l.addView(note);new AlertDialog.Builder(this).setTitle("تسجيل دفعة").setView(l).setPositiveButton("حفظ الدفعة",(d,w)->{double a=Ui.num(amount);if(a>0)db.addPayment(iid,a,new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()),note.getText().toString().trim());refresh();}).setNeutralButton("سجل الدفعات",(d,w)->paymentHistory(iid,item)).setNegativeButton("إلغاء",null).show();}
 void paymentHistory(long iid,String item){StringBuilder s=new StringBuilder();Cursor c=db.getReadableDatabase().rawQuery("SELECT date,amount,note FROM payments WHERE item_id=? ORDER BY id DESC",new String[]{""+iid});if(!c.moveToFirst())s.append("لا توجد دفعات مسجلة.");else do{s.append(c.getString(0)).append("  •  ").append(fmt(c.getDouble(1))).append(" د.ع");if(c.getString(2)!=null && !c.getString(2).isEmpty())s.append("\n").append(c.getString(2));s.append("\n\n");}while(c.moveToNext());c.close();new AlertDialog.Builder(this).setTitle("سجل دفعات: "+item).setMessage(s.toString()).setPositiveButton("إغلاق",null).show();}
}
